Repository NestedFi/nested-core-lego, pull requests merged in 2022-06, with the labels that each got.

#116 feat: OwnerProxy
  addresses.json
  contracts/governance/OwnerProxy.sol
  contracts/governance/scripts/OperatorScripts.sol
  contracts/governance/scripts/UpdateFees.sol
  contracts/interfaces/external/ITransparentUpgradeableProxy.sol
  contracts/mocks/FailedDeploy.sol
  scripts/deployOwnerProxy.ts
  scripts/op_scripts/deployOperatorScripts.ts
  scripts/operators/FlatOperator/generateCalldata.ts
  scripts/operators/ParaswapOperator/generateCalldata.ts
  scripts/operators/ParaswapOperator/verify.ts
  scripts/operators/addFlatOperator.ts
  scripts/operators/addParaswapOperator.ts
  test/unit/FlatOperator.unit.ts
  test/unit/NestedFactory.unit.ts
  test/unit/OperatorResolver.unit.ts
  test/unit/OwnerProxy.unit.ts
Labels: Fix and merge

#120 fix: bypass fees regression
  contracts/NestedFactory.sol
  test/shared/provider.ts
  test/unit/FlatOperator.unit.ts
Labels: To review

#119 [New Operator] StakeDAO + Yearn (curve pools)
  contracts/NestedFactory.sol
  contracts/interfaces/external/ICurvePool/ICurvePool.sol
  contracts/interfaces/external/ICurvePool/ICurvePoolETH.sol
  contracts/interfaces/external/ICurvePool/ICurvePoolNonETH.sol
  contracts/interfaces/external/IStakingVault/IStakeDaoStrategy.sol
  contracts/interfaces/external/IStakingVault/IStakingVault.sol
  contracts/interfaces/external/IStakingVault/IYearnVault.sol
  contracts/interfaces/external/IWETH.sol
  contracts/libraries/CurveHelpers.sol
  contracts/libraries/OperatorHelpers.sol
  contracts/libraries/StakingLPVaultHelpers.sol
  contracts/operators/StakeDAO/StakeDaoCurveStrategyOperator.sol
  contracts/operators/StakeDAO/StakeDaoStrategyStorage.sol
  contracts/operators/Yearn/YearnCurveVaultOperator.sol
  contracts/operators/Yearn/YearnVaultStorage.sol
  scripts/utils.ts
  test/helpers.ts
  test/shared/fixtures.ts
  test/shared/impersonnate.ts
  test/unit/StakeDaoCurveStrategyOperator.unit.ts
  test/unit/YearnCurveVaultOperator.unit.ts
Labels: To review

#121 Audit preparation
  .env.example
  README.MD
  contracts/FeeSplitter.sol
  contracts/NestedAsset.sol
  contracts/NestedBuybacker.sol
  contracts/NestedFactory.sol
  contracts/NestedRecords.sol
  contracts/NestedReserve.sol
  contracts/OperatorResolver.sol
  contracts/Withdrawer.sol
  contracts/abstracts/MixinOperatorResolver.sol
  contracts/abstracts/OwnableFactoryHandler.sol
  contracts/abstracts/OwnableProxyDelegation.sol
  contracts/governance/OwnerProxy.sol
  contracts/governance/TimelockControllerEmergency.sol
  contracts/governance/scripts/OperatorScripts.sol
  contracts/governance/scripts/UpdateFees.sol
  contracts/interfaces/INestedFactory.sol
  contracts/interfaces/IOperatorResolver.sol
  contracts/interfaces/external/IBeefyVaultV6.sol
  contracts/interfaces/external/IBiswapPair.sol
  contracts/interfaces/external/IBiswapRouter02.sol
  contracts/interfaces/external/INestedToken.sol
  contracts/interfaces/external/ITransparentUpgradeableProxy.sol
  contracts/interfaces/external/IWETH.sol
  contracts/libraries/CURVE_POOLS.md
  contracts/libraries/ExchangeHelpers.sol
  contracts/mocks/AugustusSwapper.sol
  contracts/mocks/TestableMixingOperatorResolver.sol
  contracts/mocks/TestableOperatorCaller.sol
  contracts/mocks/TokenTransferProxy.sol
  contracts/operators/Beefy/BeefyVaultOperator.sol
  contracts/operators/Beefy/BeefyVaultStorage.sol
  contracts/operators/Beefy/lp/BeefyZapBiswapLPVaultOperator.sol
  contracts/operators/Beefy/lp/BeefyZapUniswapLPVaultOperator.sol
  contracts/operators/Flat/FlatOperator.sol
  contracts/operators/Flat/IFlatOperator.sol
  contracts/operators/Paraswap/IParaswapOperator.sol
  contracts/operators/Paraswap/ParaswapOperator.sol
  contracts/operators/ZeroEx/IZeroExOperator.sol
  contracts/operators/ZeroEx/ZeroExOperator.sol
  contracts/operators/ZeroEx/ZeroExStorage.sol
  contracts/utils/NestedAssetBatcher.sol
  hardhat.config.ts
  scripts/deployOwnerProxy.ts
  scripts/op_scripts/deployOperatorScripts.ts
  scripts/operators/FlatOperator/generateCalldata.ts
  scripts/operators/ParaswapOperator/generateCalldata.ts
  scripts/utils.ts
  static/input-orders.png
  static/output-orders.png
  static/ownership.png
  static/processInputOrders.png
  test/shared/fixtures.ts
  test/unit/BeefyZapBiswapLPVaultOperator.ts
  test/unit/BeefyZapUniswapLPVaultOperator.ts
  test/unit/NestedFactory.unit.ts
  test/unit/OwnerProxy.unit.ts
Labels: Fix and merge

#122 fix: Feature/fix yearn stake dao merge
  contracts/interfaces/external/ICurvePool/ICurvePool.sol
  contracts/interfaces/external/ICurvePool/ICurvePoolETH.sol
  contracts/interfaces/external/ICurvePool/ICurvePoolNonETH.sol
  contracts/interfaces/external/IStakingVault/IStakeDaoStrategy.sol
  contracts/interfaces/external/IStakingVault/IStakingVault.sol
  contracts/interfaces/external/IStakingVault/IYearnVault.sol
  contracts/libraries/CurveHelpers/CurveHelpers.sol
  contracts/libraries/CurveHelpers/README.md
  contracts/libraries/OperatorHelpers.sol
  contracts/libraries/StakingLPVaultHelpers.sol
  contracts/operators/StakeDAO/StakeDaoCurveStrategyOperator.sol
  contracts/operators/StakeDAO/StakeDaoStrategyStorage.sol
  contracts/operators/Yearn/YearnCurveVaultOperator.sol
  contracts/operators/Yearn/YearnVaultStorage.sol
  hardhat.config.ts
Labels: Can merge
